server:
  port: 8080

#    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
#    username: murtazait
#    password: murtazait@110
#    driverClassName: com.mysql.cj.jdbc.Driver
#  application:
#    name: PRODUCT-SERVICE
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: murtazait
    password: murtazait@110
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  


logging:
  file:
    name: mylog.log

# Log level
  level:
    root: INFO
      
      